### ISSUE TITLE
Attention Mechanism

### ISSUE THREAD

**Issue by naveedsultan587** [likakakaka/HAUNet_RSISR#4]
how can we make changes to the attention mechanisms, I tried to find the CAB and SAB that you used in the code with QKV but didn't find please let me know about it.

**Comment by likakakaka** [comment]
QKV code in the CAB and SAB block is in the 295 and 378 lines in /codes/model/haunet.py which named CEMBlock and S_CEMBlock.

**Comment by naveedsultan587** [comment]
thank you
